### ISSUE TITLE
Scrappy Subscriptions

### ISSUE THREAD

**Issue by beausmith** [din-co/d2#271]
## Tasks
- [ ] update copy per @stacycorona/@beausmith conversation re: "suggest v select"
- [ ] email templates for sending email to customers regarding subscriptions
## Open Questions
- [ ] Timing of restaurant pick up
- [ ] UI for customers to cancel order or change selections or via support
